print("Welcome to HaDX Car OS. Copyright HaDX Car Software")
print(" HaDX Car Software                [Write your car name and model]                                            ")
print("                                                                                                             ")
print("                                                                                                             ")
print("                                                                                                             ")
print("     Phone                                                                                                   ")
print(" Settings                                                                                                    ")
print("  Music                                                                                                      ")
print("     Radio                                                                                                   ")
print("       [Your phone model] Setting                                                                            ")
print("                HaDX Maps                                                                                    ")
print("                     [Your car] Settings                                                                     ")
print("                                HaDX Store                                                                   ")
print("                                                                                                             ")
print("                                                                                                             ")
print("                                                                                                             ")
print("                                                                                                             ")
print("                                                                                                             ")
print("                                                                                                             ")
print("                                                                                                             ")
print("                                                                                                             ")
print("                                                                                                             ")
print("                                                                                                             ")
print("                                                                                                             ")
print("                                                                                                             ")
print("                                                                                                             ")
print("                                                                                                             ")
print("                                                                                                             ")
print("                                                                                                             ")
print("                                                                                                             ")
print("                                                                                                             ")
print("                                                                                                             ")
print(" Connected phone: Coming soon(or write you phone in idle)                                                    ")
