print("     [Car Name]    ")
print("                   ")
print("     Radio:[Radio] ")
print("                   ")
print("Phone Status:DSCNCD")
print("                   ")
print("                   ")
print("                   ")
print("                   ")
print("                   ")
print("                   ")
print("     HaDX 0.0.1    ")
